<?php
function sa_theme_print_about_page() {
?>
<section id="markdown-nice" style="font-size: 16px; color: black; padding: 25px 30px; line-height: 1.6; word-spacing: 0px; letter-spacing: 0px; word-break: break-word; word-wrap: break-word; text-align: justify; font-family: Optima-Regular, Optima, PingFangSC-light, PingFangTC-light, 'PingFang SC', Cambria, Cochin, Georgia, Times, 'Times New Roman', serif; margin-top: -10px;"><h1 style="margin-top: 30px; margin-bottom: 15px; font-weight: bold; color: black; font-size: 24px;"><span class="prefix" style="display: none;"></span><span class="content">WordPress 简约主题 Sapphire</span><span class="suffix"></span></h1>
<figure style="margin: 0; margin-top: 10px; margin-bottom: 10px;"><img src="http://qcdn.itcharge.cn/images/sapphire-screenshot.png" alt style="margin: 0 auto; width: auto; max-width: 600px;"></figure>
<h2 style="margin-top: 30px; margin-bottom: 15px; font-weight: bold; color: black; font-size: 22px;"><span class="prefix" style="display: none;"></span><span class="content">1. 环境要求</span><span class="suffix"></span></h2>
<table style="display: table; text-align: left;">
<thead>
<tr style="border: 0; border-top: 1px solid #ccc; background-color: white;">
<th style="font-size: 16px; border: 1px solid #ccc; padding: 5px 10px; text-align: left; font-weight: bold; background-color: #f0f0f0;">主题名称</th>
<th style="font-size: 16px; border: 1px solid #ccc; padding: 5px 10px; text-align: left; font-weight: bold; background-color: #f0f0f0;">Sapphire</th>
<th style="font-size: 16px; border: 1px solid #ccc; padding: 5px 10px; text-align: left; font-weight: bold; background-color: #f0f0f0;">最新版本</th>
<th style="font-size: 16px; border: 1px solid #ccc; padding: 5px 10px; text-align: left; font-weight: bold; background-color: #f0f0f0;">v1.0</th>
</tr>
</thead>
<tbody style="border: 0;">
<tr style="border: 0; border-top: 1px solid #ccc; background-color: white;">
<td style="font-size: 16px; border: 1px solid #ccc; padding: 5px 10px; text-align: left;">环境要求</td>
<td style="font-size: 16px; border: 1px solid #ccc; padding: 5px 10px; text-align: left;">Wordpress 5.8+，PHP 5.6+</td>
<td style="font-size: 16px; border: 1px solid #ccc; padding: 5px 10px; text-align: left;">服务器支持</td>
<td style="font-size: 16px; border: 1px solid #ccc; padding: 5px 10px; text-align: left;">Linux / Windows / Mac</td>
</tr>
<tr style="border: 0; border-top: 1px solid #ccc; background-color: #F8F8F8;">
<td style="font-size: 16px; border: 1px solid #ccc; padding: 5px 10px; text-align: left;">浏览器支持</td>
<td style="font-size: 16px; border: 1px solid #ccc; padding: 5px 10px; text-align: left;">主流浏览器（除 IE 外）</td>
<td style="font-size: 16px; border: 1px solid #ccc; padding: 5px 10px; text-align: left;">页面模板</td>
<td style="font-size: 16px; border: 1px solid #ccc; padding: 5px 10px; text-align: left;">归档页面、分类页面、标签页面</td>
</tr>
<tr style="border: 0; border-top: 1px solid #ccc; background-color: white;">
<td style="font-size: 16px; border: 1px solid #ccc; padding: 5px 10px; text-align: left;">演示地址</td>
<td style="font-size: 16px; border: 1px solid #ccc; padding: 5px 10px; text-align: left;"><a href="https://itcharge.cn" style="text-decoration: none; color: #1e6bb8; word-wrap: break-word; font-weight: bold; border-bottom: 1px solid #1e6bb8;">点击查看</a></td>
<td style="font-size: 16px; border: 1px solid #ccc; padding: 5px 10px; text-align: left;">下载地址</td>
<td style="font-size: 16px; border: 1px solid #ccc; padding: 5px 10px; text-align: left;"><a href="https://github.com/itcharge/WordPress-Theme-Sapphire/releases" style="text-decoration: none; color: #1e6bb8; word-wrap: break-word; font-weight: bold; border-bottom: 1px solid #1e6bb8;">点击跳转下载链接</a></td>
</tr>
</tbody>
</table>
<h2 style="margin-top: 30px; margin-bottom: 15px; font-weight: bold; color: black; font-size: 22px;"><span class="prefix" style="display: none;"></span><span class="content">2. 主题简介</span><span class="suffix"></span></h2>
<p style="font-size: 16px; padding-top: 8px; padding-bottom: 8px; margin: 0; line-height: 26px; color: black;"><strong style="font-weight: bold; color: black;">Sapphire</strong> 是一款简约好用的双栏 Wordpress 主题，适用于个人博客类网站使用。在设计上遵循着 <strong style="font-weight: bold; color: black;">「简约至上」</strong> 的设计原则，在保证网站功能完整、内容清楚的前提下，做到尽可能的简单。</p>
<p style="font-size: 16px; padding-top: 8px; padding-bottom: 8px; margin: 0; line-height: 26px; color: black;">Sapphire 主题界面简洁大气，外表简洁而不简单，内置归档、分类、标签模板页面，还有最新文章、热门标签等多功能边栏面板。网站采用响应式设计，完美支持手机、平板和电脑浏览。Sapphire 主题采用了纯代码级的 SEO 优化，可以让你的网站推广事半功倍。本主题内置主题设置页面，支持自定义网站效果，小白站长也能轻松的创建自己的网站。</p>
<h2 style="margin-top: 30px; margin-bottom: 15px; font-weight: bold; color: black; font-size: 22px;"><span class="prefix" style="display: none;"></span><span class="content">3. 主题特色</span><span class="suffix"></span></h2>
<ul style="margin-top: 8px; margin-bottom: 8px; padding-left: 25px; color: black; list-style-type: disc;">
<li><section style="margin-top: 5px; margin-bottom: 5px; line-height: 26px; text-align: left; color: rgb(1,1,1); font-weight: 500;">响应式设计：完美兼容手机、平板、电脑等各类设备访问。</section></li><li><section style="margin-top: 5px; margin-bottom: 5px; line-height: 26px; text-align: left; color: rgb(1,1,1); font-weight: 500;">简洁大气：界面简洁大气，首页支持自定义展现方式。</section></li><li><section style="margin-top: 5px; margin-bottom: 5px; line-height: 26px; text-align: left; color: rgb(1,1,1); font-weight: 500;">SEO 支持：纯代码级优化，文章关键词自动内链。</section></li><li><section style="margin-top: 5px; margin-bottom: 5px; line-height: 26px; text-align: left; color: rgb(1,1,1); font-weight: 500;">主题后台设置：支持后台自定义选项设置，小白也能轻松建站。</section></li><li><section style="margin-top: 5px; margin-bottom: 5px; line-height: 26px; text-align: left; color: rgb(1,1,1); font-weight: 500;">文章页面支持代码高亮、支持 LaTex 数学公式。</section></li></ul>
<h2 style="margin-top: 30px; margin-bottom: 15px; font-weight: bold; color: black; font-size: 22px;"><span class="prefix" style="display: none;"></span><span class="content">4. 所有功能</span><span class="suffix"></span></h2>
<ul style="margin-top: 8px; margin-bottom: 8px; padding-left: 25px; color: black; list-style-type: disc;">
<li><section style="margin-top: 5px; margin-bottom: 5px; line-height: 26px; text-align: left; color: rgb(1,1,1); font-weight: 500;">响应式设置：兼容手机、平板、电脑等各类设备访问。</section></li><li><section style="margin-top: 5px; margin-bottom: 5px; line-height: 26px; text-align: left; color: rgb(1,1,1); font-weight: 500;">网站图标设置：favicion 图标、顶部 Logo、边栏 Logo。</section></li><li><section style="margin-top: 5px; margin-bottom: 5px; line-height: 26px; text-align: left; color: rgb(1,1,1); font-weight: 500;">页面模板支持：增加归档、分类、标签等页面模板。</section></li><li><section style="margin-top: 5px; margin-bottom: 5px; line-height: 26px; text-align: left; color: rgb(1,1,1); font-weight: 500;">页面效果优化：页面点击小红心效果、加载进度条显示。</section></li><li><section style="margin-top: 5px; margin-bottom: 5px; line-height: 26px; text-align: left; color: rgb(1,1,1); font-weight: 500;">网站底部自定义：网站成立年份、备案号。</section></li><li><section style="margin-top: 5px; margin-bottom: 5px; line-height: 26px; text-align: left; color: rgb(1,1,1); font-weight: 500;">网站访问数统计：总访问量统计、总访客数统计。</section></li><li><section style="margin-top: 5px; margin-bottom: 5px; line-height: 26px; text-align: left; color: rgb(1,1,1); font-weight: 500;">边栏自定义显示：最新文章、热门标签、联系方式、文章页目录显示。</section></li><li><section style="margin-top: 5px; margin-bottom: 5px; line-height: 26px; text-align: left; color: rgb(1,1,1); font-weight: 500;">SEO 优化：标题连接符号设置、网站关键词设置、网站面熟设置、文章关键词自动内链。</section></li><li><section style="margin-top: 5px; margin-bottom: 5px; line-height: 26px; text-align: left; color: rgb(1,1,1); font-weight: 500;">文章效果显示优化：代码高亮、LaTex 公式、阅读时长、字数统计、文章目录自动生成、目录跟随功能。</section></li><li><section style="margin-top: 5px; margin-bottom: 5px; line-height: 26px; text-align: left; color: rgb(1,1,1); font-weight: 500;">文章页底部增加赞赏功能：支持微信、支付宝。</section></li><li><section style="margin-top: 5px; margin-bottom: 5px; line-height: 26px; text-align: left; color: rgb(1,1,1); font-weight: 500;">文章页底部增加版权说明：原文作者、原文地址、版权协议、版权链接。</section></li><li><section style="margin-top: 5px; margin-bottom: 5px; line-height: 26px; text-align: left; color: rgb(1,1,1); font-weight: 500;">联系方式自定义：支持微博、知乎、CSDN 等多个社交方式设置。</section></li></ul>
<h2 style="margin-top: 30px; margin-bottom: 15px; font-weight: bold; color: black; font-size: 22px;"><span class="prefix" style="display: none;"></span><span class="content">5. 更新记录</span><span class="suffix"></span></h2>
<h6 style="margin-top: 30px; margin-bottom: 15px; font-weight: bold; color: black; font-size: 16px;"><span class="prefix" style="display: none;"></span><span class="content">1. V1.0 2021-07-30（最新版本）</span><span class="suffix" style="display: none;"></span></h6>
<ul style="margin-top: 8px; margin-bottom: 8px; padding-left: 25px; color: black; list-style-type: disc;">
<li><section style="margin-top: 5px; margin-bottom: 5px; line-height: 26px; text-align: left; color: rgb(1,1,1); font-weight: 500;">实现主题的基本功能，包含页面搭建、基本设置、主题设置。</section></li><li><section style="margin-top: 5px; margin-bottom: 5px; line-height: 26px; text-align: left; color: rgb(1,1,1); font-weight: 500;">支持归档、分类、标签页面显示。</section></li><li><section style="margin-top: 5px; margin-bottom: 5px; line-height: 26px; text-align: left; color: rgb(1,1,1); font-weight: 500;">网站自定义备案信息、访问数统计。</section></li><li><section style="margin-top: 5px; margin-bottom: 5px; line-height: 26px; text-align: left; color: rgb(1,1,1); font-weight: 500;">页面效果优化、边栏自定义、联系方式自定义。</section></li><li><section style="margin-top: 5px; margin-bottom: 5px; line-height: 26px; text-align: left; color: rgb(1,1,1); font-weight: 500;">响应式设置：兼容手机、平板、电脑等各类设备访问。</section></li><li><section style="margin-top: 5px; margin-bottom: 5px; line-height: 26px; text-align: left; color: rgb(1,1,1); font-weight: 500;">文章显示效果优化、底部赞赏功能、版权说明。</section></li></ul>
<h2 style="margin-top: 30px; margin-bottom: 15px; font-weight: bold; color: black; font-size: 22px;"><span class="prefix" style="display: none;"></span><span class="content">6. 关于主题</span><span class="suffix"></span></h2>
<blockquote style="display: block; font-size: 0.9em; overflow: auto; overflow-scrolling: touch; border-left: 3px solid rgba(0, 0, 0, 0.4); background: rgba(0, 0, 0, 0.05); color: #6a737d; padding-top: 10px; padding-bottom: 10px; padding-left: 20px; padding-right: 10px; margin-bottom: 20px; margin-top: 20px;">
<p style="font-size: 16px; padding-top: 8px; padding-bottom: 8px; margin: 0px; color: black; line-height: 26px;">特别说明：</p>
<p style="font-size: 16px; padding-top: 8px; padding-bottom: 8px; margin: 0px; color: black; line-height: 26px;">本主题在部分界面设计上参考了：<a href="https://github.com/litten/hexo-theme-yilia" style="text-decoration: none; color: #1e6bb8; word-wrap: break-word; font-weight: bold; border-bottom: 1px solid #1e6bb8;">hexo-theme-yilia</a>。除此之外还借鉴了 <a href="https://mkblog.cn/theme-mkblog/" style="text-decoration: none; color: #1e6bb8; word-wrap: break-word; font-weight: bold; border-bottom: 1px solid #1e6bb8;">mkBlog</a>、<a href="https://www.topicnote.com/1621.html" style="text-decoration: none; color: #1e6bb8; word-wrap: break-word; font-weight: bold; border-bottom: 1px solid #1e6bb8;">Simple</a>、<a href="https://cn.wordpress.org/themes/onepress/" style="text-decoration: none; color: #1e6bb8; word-wrap: break-word; font-weight: bold; border-bottom: 1px solid #1e6bb8;">OnePress</a>、<a href="https://wordpress.org/themes/dashscroll/" style="text-decoration: none; color: #1e6bb8; word-wrap: break-word; font-weight: bold; border-bottom: 1px solid #1e6bb8;">Dashscroll</a> 等优秀主题的设计理念。</p>
<p style="font-size: 16px; padding-top: 8px; padding-bottom: 8px; margin: 0px; color: black; line-height: 26px;">主题中使用了<a href="https://jquery.com/" style="text-decoration: none; color: #1e6bb8; word-wrap: break-word; font-weight: bold; border-bottom: 1px solid #1e6bb8;">jQuery</a>、 <a href="https://github.com/googlearchive/code-prettify" style="text-decoration: none; color: #1e6bb8; word-wrap: break-word; font-weight: bold; border-bottom: 1px solid #1e6bb8;">Google Code Prettify</a>、<a href="https://necolas.github.io/normalize.css/" style="text-decoration: none; color: #1e6bb8; word-wrap: break-word; font-weight: bold; border-bottom: 1px solid #1e6bb8;">Normalize.css</a>、<a href="https://codebyzach.github.io/pace/" style="text-decoration: none; color: #1e6bb8; word-wrap: break-word; font-weight: bold; border-bottom: 1px solid #1e6bb8;">PACE</a>、<a href="https://github.com/cry101/blogMenu" style="text-decoration: none; color: #1e6bb8; word-wrap: break-word; font-weight: bold; border-bottom: 1px solid #1e6bb8;">blogMenu</a>、<a href="https://www.mathjax.org/" style="text-decoration: none; color: #1e6bb8; word-wrap: break-word; font-weight: bold; border-bottom: 1px solid #1e6bb8;">MathJax</a> 等第三方插件。</p>
</blockquote>
</section>

<?php
}
?>
